### ISSUE TITLE
StartedTags and StopppedTags are not working

### ISSUE THREAD

**Issue by dgeenukunta** [awslabs/aws-instance-scheduler#84] opened 2019-04-08 02:24 UTC
Hi,

I have created a template for schedule and periods and referenced the main instance-scheduler template. everything seems working fine. StartedTags and StoppedTags are not getting updated with the instance state.

{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "EC2 Instance Schedules",
  "Resources": {
    "officehours": {
      "Type": "Custom::ServiceInstanceSchedule",
      "Properties": {
        "ServiceToken": "arn:aws:lambda:ap-southeast-2:XXXXXXXXX:function:AWS-InstanceSchedulerMain",
        "Description": "working hours",
        "Enforced": "True",
        "Timezone": "Australia/Sydney",
        "Periods": [
          {
            "Description": "Opening hours on weekdays",
            "BeginTime": "09:00",
            "EndTime": "23:59",
            "WeekDays": "Mon-Fri"
          },
          {
            "Description": "Opening hours in weekdays",
            "BeginTime": "00:00",
            "EndTime": "4:29",
            "WeekDays": "Mon-Fri"
          }
        ]
      }
    }
  }
}

**Comment by arieleeuw** [comment] 2019-04-08 18:04
Hi,
Make sure that you have installed the latest version of the scheduler from https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.template as there was an issue with setting the tags in earlier versions.
Also note that setting the tags are global settings and not part of the Schedule/Periods created with the your template with the custom resource.

**Comment by dgeenukunta** [comment] 2019-04-08 18:10
Hi,

I have the latest version of template and when i use scheduler-cli to create the periods and schedule, tags are setting with the instance state.

When i use the above template as a nested template to instance-scheduler.template, tags are not setting with instance state. Though the instance is running the scheduler on specified period.

Please let me know your thoughts.

Thanks,
Deepa

**Comment by arieleeuw** [comment] 2019-04-08 18:26
Deepak,
Setting the tags should be independent on how you create the schedule. Which setting do you use for the tags and what values do you expec?


On 8 Apr 2019, at 20:10, dgeenukunta <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I have the latest version of template and when i use scheduler-cli to create the periods and schedule, tags are setting with the instance state.

When i use the above template as a nested template to instance-scheduler.template, tags are not setting with instance state. Though the instance is running the scheduler on specified period.

Please let me know your thoughts.

Thanks,
Deepa

**Comment by dgeenukunta** [comment] 2019-04-08 18:30
I have used below tags in instance scheduler template as parameters.
Started tags: ScheduleMessage=Started on {year}/{month}/{day} at {hour}:{minute} {timezone}
Stopped tags: ScheduleMessage=Stopped on {year}/{month}/{day} at {hour}:{minute} {timezone}

**Comment by praveenis** [comment] 2020-08-28 19:38
Hi Deepa,

We couldn't reproduce this issue with the latest Instance Scheduler v1.3.2. If you are still seeing this issue, can you please provide the cloud watch logs for the time range when instance start and stop. 

Thanks,
Praveen

**Comment by maykays** [comment] 2020-09-28 20:02
Closing this issue. Please re-open if the problem persists.

**Closed by maykays** 2020-09-28 20:02 UTC
Labels: review
