### ISSUE TITLE
Instance Scheduler not stopping/starting instances (SchedulerRole/SchedulerRule physical id get trimmed if stack name is too long)

### ISSUE THREAD

**Issue by C-Kenny** [awslabs/aws-instance-scheduler#89] opened 2019-04-25 22:33 UTC
Looking at the log group for the Instance Scheduler, I can see it's receiving events it doesn't understand.

Event is:
```

{
    "account": "123456789",
    "region": "ap-southeast-2",
    "detail": {},
    "detail-type": "Scheduled Event",
    "source": "aws.events",
    "version": "0",
    "time": "2019-04-25T18:55:00Z",
    "id": "1ae3775c-d0b0-b548-fa22-7d8fb542012c",
    "resources": [
        "arn:aws:events:ap-southeast-2:123456789:rule/aws-instance-scheduler-SchedulerRule-"
    ]
}
```

Error:

```
DEBUG : Request was not handled, no handler was able to handle this type of request
```

From what I can see, the DynamoDB config table as a schedule + period. The instances are tagged with the schedule name.

Version: `InstanceScheduler, version 2.2.2.0`

**Comment by C-Kenny** [comment] 2019-04-26 03:34
In further investigation, in the CloudWatch request handler, we can see that it tries to get the name by string manipulation. https://github.com/awslabs/aws-instance-scheduler/blob/master/source/code/requesthandlers/cloudwatch_event_handler.py

```
    @staticmethod
    def is_handling_request(event):
        """
        Handler for cloudwatch event to run the scheduler
        :return: True
        """

        return event.get("detail-type", "") == "Scheduled Event" and \
               event.get("resources", ["/"])[0].split("/")[-1].startswith("{}-SchedulerRule".format(os.getenv(configuration.ENV_STACK)))
```

We found that the SchedulerRule name auto created didn't have the ENV_STACK/StackName as part of the name.

Because of this, the is_handling_request function always returned False and therefore the process to start/stop the instances never occurred.

I was able to find a similar issue: https://github.com/awslabs/aws-instance-scheduler/issues/52 but it didn't touch on the SchedulerRule name generated.

As the Physical ID is not passed in as a parameter to the CloudFormation template, this wasn't immediately obvious.

It appears that if you create a long-ish stack name e.g. `"mycompanysandpit-aws-instance-scheduler-v2"`

Then the Scheduler Role and Scheduler Rules will get trimmed

`"mycompanysandpit-aws-instance-schedul-SchedulerRule-12K7Y53C9U420"`

Here we can see that the stack name gets trimmed, so won't be found in the string.

If you create the stack with a smaller name e.g. `"mycompanysandpit-ec2-scheduler"` then the SchedulerRule name generated will include the whole stack name: `"mycompanysandpit-ec2-scheduler-SchedulerRule-2VS3EODU117"`

**Comment by aws-david** [comment] 2019-04-26 06:35
You are 100% correct, the error is because of the Stack name length. The exact number allowed for the Instance-Scheduler solution, is 36 characters. I found that this is mentioned in the documentation [1] for the solution, however it is not obvious, unless you follow the deployment guide [2]. 

Step 1 has the following note:

    4. On the Specify Details page, assign a name to your solution stack.
        Note
                The stack name cannot contain more than 36 characters.

The issue is, that CloudFormation can not specify a requirement on the "Stack name" like it can do with parameters, in the CloudFormation template that is.

References:
[1] https://docs.aws.amazon.com/solutions/latest/instance-scheduler/revisions.html
[2] https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html#step1

**Comment by C-Kenny** [comment] 2019-10-01 20:31
Thanks for following this up. Would it possible to put a character limit on the CloudFormation parameter that's enforced at that stage?

**Comment by C-Kenny** [comment] 2019-10-01 20:36
Thanks for following up. Interesting that CloudFormation cannot at this stage limit its own stack name.

**Comment by georgebearden** [comment] 2019-10-16 17:53
Closing this issue but please let us know if you need more assistance.

**Closed by georgebearden** 2019-10-16 17:53 UTC
